# Sidebar navigation

- label: 'Prework'
  items:
    - label: 'Introduction'
      link: '/prework/introduction'
    - label: 'Contents'
      link: '/prework/contents'
    - label: 'Prework test'
      link: '/prework/prework-test'
    - label: 'Further reading'
      link: '/prework/further-reading'
- label: 'Git'
  items:
    - label: 'Introduction'
      link: '/git/introduction'
    - label: 'Contents'
      link: '/git/contents'
    - label: 'Further reading'
      link: '/git/further-reading'
- label: HTML
  items:
    - label: 'Introduction'
      link: '/html/introduction'
    - label: 'Contents'
      link: '/html/contents'
    - label: 'HTML Section project'
      link: '/html/html-section-project'
    - label: 'Further reading'
      link: '/html/further-reading'
- label: CSS
  items:
    - label: 'Introduction'
      link: '/css/introduction'
    - label: 'Contents'
      link: '/css/contents'
    - label: 'CSS Section project'
      link: '/css/css-section-project'
    - label: 'Further reading'
      link: '/css/further-reading'
- label: SASS
  items:
    - label: 'Introduction'
      link: '/sass/introduction'
    - label: 'Contents'
      link: '/sass/contents'
    - label: 'Further reading'
      link: '/sass/further-reading'
- label: Basic Javascript
  items:
    - label: 'Introduction'
      link: '/basic-js/introduction'
    - label: 'Contents'
      link: '/basic-js/contents'
    - label: 'Basic JS Section project'
      link: '/basic-js/basic-js-section-project'
    - label: 'Further reading'
      link: '/basic-js/further-reading'
- label: Midcourse project
  items:
    - label: 'Introduction'
      link: '/pokedex/assignment'
- label: Advanced Javascript
  items:
    - label: 'Introduction'
      link: '/advanced-js/introduction'
    - label: 'Arrays in depth'
      link: '/advanced-js/arrays'
    - label: 'Further reading'
      link: '/advanced-js/arrays-further-reading'
    - label: 'Functions in depth'
      link: '/advanced-js/functions'
    - label: 'Further reading'
      link: '/advanced-js/functions-further-reading'
    - label: 'Objects in depth'
      link: '/advanced-js/objects'
    - label: 'API calls'
      link: '/advanced-js/api-calls'
- label: VueJS
  items:
    - label: 'Introduction'
      link: '/vue/introduction'
    - label: 'Application Component'
      link: '/vue/application-component'
    - label: 'Template syntax'
      link: '/vue/template-syntax'
    - label: 'Data properties and methods'
      link: '/vue/data-properties-methods'
    - label: 'Computed properties and watchers'
      link: '/vue/computed-properties-watchers'
    - label: 'Class and Style bindings'
      link: '/vue/class-style'
    - label: 'Conditional rendering'
      link: '/vue/conditionals'
    - label: 'Loops'
      link: '/vue/loops'
    - label: 'Event handling'
      link: '/vue/events'
    - label: 'Forms'
      link: '/vue/forms'
    # - label: 'Components'
    #   link: '/vue/components'
